name: CI/CD [FE]

on:
  push:
    paths:
      - frontend/**

defaults:
  run:
    working-directory: ./frontend

jobs:
  test:
      name: Run tests
      runs-on: ubuntu-latest
      steps:
        - name: "checkout repo"
          uses: actions/checkout@v4

        - name: "setup node"
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name : "install npm@latest"
          run : npm i -g npm@latest

        - name : "install dependencies"
          uses: bahmutov/npm-install@v1.10.5
          with:
            working-directory: ./frontend

        - name : "run tests"
          run : npm run test
        
  eslint:
      name: "Run eslint"
      runs-on: ubuntu-latest
      steps:
        - name: "checkout repo"
          uses: actions/checkout@v4

        - name: "setup node"
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name : "install npm@latest"
          run : npm i -g npm@latest

        - name : "install dependencies"
          uses : bahmutov/npm-install@v1.10.5
          with:
            working-directory: ./frontend

        - name : "Run eslint"
          uses: sibiraj-s/action-eslint@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }} # optional
            eslint-args: "--ignore-path=.gitignore --quiet"
            extensions: "js,jsx,ts,tsx"
            annotations: true
