# Workflow for updating release as a one click
name: Release new version of Wanderers

on:
  # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
      inputs:
        version:
            description: 'Version to release'
            required: true

# Sets permissions of the GITHUB_TOKEN to write tags
permissions: write-all

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            ref: release-${{ github.event.inputs.version }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
            python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Create .env file for python dependencies
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GIT_TOKEN }}" > .env
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
      - name: Generate Release Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          python scripts/release/generate_release.py --release_version ${{ github.event.inputs.version }}
