# Workflow for automatically tagging prd branch after it has been updated
name: Tag prd after push

on:
    push:
        branches: ["prd"]

# Sets permissions of the GITHUB_TOKEN to access
permissions: write-all

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Set up Python 3.10
            uses: actions/setup-python@v3
            with:
                python-version: "3.10"
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
                pip install -r requirements.txt
          - name: Set up Git user
            run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "actions@github.com"
          - name: Get latest changelog version
            id: get_latest_changelog_version
            run: |
              echo "latest_version=$(python scripts/release/get_latest_version.py)" >> $GITHUB_ENV
          - name: Tag latest commit with latest version
            env:
                GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
                latest_version: ${{ env.latest_version }}
            run: |
              git tag -a v${{ env.latest_version }} -m "Release v${{ env.latest_version }}"
              git push --tags
