name: Vercel
on:
  push:
    branches: [prd, stg] # We also want to deploy and update stg and prd website per push
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    working-directory: ./frontend

permissions: write-all

jobs:
  deploy:
    environment:
      name: ${{ github.ref == 'refs/heads/prd' && 'Production' || github.ref == 'refs/heads/stg' && 'Preview' || 'Development' }}
      url: ${{ github.ref == 'refs/heads/prd' && steps.show_page_url_prd_or_stg.outputs.new_page_url || github.ref == 'refs/heads/stg' && steps.show_page_url_prd_or_stg.outputs.new_page_url || steps.show_page_url_dev.outputs.new_page_url }}
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm ci
          npx vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Check prd or not
        id: prod_or_not
        run: |
          if [ "$REF" == 'refs/heads/prd' ]
          then
              echo "vercel-args=--prod --prebuilt" >> $GITHUB_OUTPUT
              echo "vercel-url=https://wanderers-prd.vercel.app/"" >> $GITHUB_OUTPUT
              echo "vercel-build"=--prod >> $GITHUB_OUTPUT
          else
              echo "vercel-args=--prebuilt" >> $GITHUB_OUTPUT
              echo "vercel-url=https://wanderers-stg.vercel.app/"" >> $GITHUB_OUTPUT
              echo "vercel-build"="" >> $GITHUB_OUTPUT
          fi
        env:
          REF: ${{ github.ref }}
      - name: "Build next.js project"
        run: |
          npx vercel build ${{ steps.prod_or_not.outputs.vercel-build }}
      - name: Deploy to Vercel [Branch]
        if: ${{ github.event_name == 'pull_request' }}
        id: deploy_branch
        uses: amondnet/vercel-action@v25
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: ${{ steps.prod_or_not.outputs.vercel-args }}
          working-directory: ./frontend

      - name: Deploy to Vercel [stg/prd]
        id: deploy_prd_or_stg
        if: ${{ github.event_name == 'push' }}
        uses: amondnet/vercel-action@v25
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: ${{ steps.prod_or_not.outputs.vercel-args }}
          working-directory: ./frontend
          alias-domains: |
            ${{ steps.prod_or_not.outputs.vercel-url }}

      - name: Show page url in "Production" and "Preview" environment (Pull Request)
        id: show_page_url_prd_or_stg
        if: ${{ github.event_name == 'push' }}
        run: echo "new_page_url=${{ steps.deploy_prd_or_stg.outputs.preview-url }}" >> $GITHUB_OUTPUT

      - name: Show page url in Development environment
        id: show_page_url_dev
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "new_page_url=${{ steps.deploy_branch.outputs.preview-url }}" >> $GITHUB_OUTPUT
